Few parsing and path fixes
mbideau/vcardtools pull request #16
Opened 2023-04-25 18:32 UTC by RaistGH

I've got this fixes while running the code through about 5000 vcards

2023-04-28 18:05 UTC, mbideau commented
Hey @RaistGH ,
Thank you very much for your fixes, very apprecitated :pray: 
As soon as you fix the two feedback/review notes I have written above I would happily merge this PR :smiley:

2023-04-28 18:32 UTC, mbideau requested changes

2023-04-28 18:32 UTC, mbideau commented on vcardlib.py
> +        else:
Also it makes all the tests fails... so better fix it in the PR please :wink: 
Thanks in advance

2023-04-29 13:49 UTC, mbideau commented on vcardlib.py
> +        else:
I've fixed it :wink:

2023-04-29 13:50 UTC, merged

2023-05-13 17:08 UTC, RaistGH commented on vcardlib.py
> +        else:
Thank for the update! Sorry, I was away and couldn't check this to fix the PR myself.